$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:

  wt:
    type: array
    description: list of unique keywords for wildtype samples
  mut:
    type: array
    description: list of unique keywords for mutant samples
  fq_dir:
    type: string
    description: path to the fastq files of the RNAseq, raw_data

  samples:
    type: string
  units:
    type: string

  ref:
    type: object
    properties:
      species:
        type: string
      release:
        type: integer
      build:
        type: string
    required:
      - species
      - release
      - build

  trimming:
    type: object
    properties:
      activate:
        type: boolean
    required:
      - activate

  pca:
    type: object
    properties:
      activate:
       type: boolean
      labels:
        type: 
          - array
          - string
        items:
          type: string
    required:
      - activate

  diffexp:
    type: object
    properties:
      contrasts:
        type: object
      model:
        type: string
    required:
      - contrasts

  params:
    type: object
    properties:
      cutadapt-pe:
        type: string
      cutadapt-se:
        type: string
      star: 
        type: string
    required:
      - cutadapt-pe
      - cutadapt-se
      - star

required:
  - wt
  - mut
  - fq_dir
  - samples
  - units
  - ref
  - pca
  - diffexp
  - params
  - trimming
